---
title: "timeseries_cluster2"
author: "Kate Sheridan"
date: "1/28/2022"
output: html_document
---

```{r setup, include=FALSE}
# which of these are used?
library(nomclust) 
library(stringr)
library(vegan)
library(ggdendro)
library(Rtsne)
library(tsne)

# definitely use these
library(tidyverse)
library(ggplot2)
library(dplyr)
library(here)
```

# load-in

```{r}
# traits
# algae time series
algae_1982 <- read_csv(here('data', 'clean', '20220128_1982-1995_algae.csv'))
algae_1996 <- read_csv(here('data', 'clean', '20220128_1996-2006_algae.csv'))
algae_2011 <- read_csv(here('data', 'clean', '20220128_2011-end_algae.csv'))

# animal time series
animal_1982 <- read_csv(here('data', 'clean', '20220128_1982-1995_animal.csv'))
animal_1996 <- read_csv(here('data', 'clean', '20220128_1996-2006_animal.csv'))
animal_2011 <- read_csv(here('data', 'clean', '20220128_2011-end_animal.csv'))

# animal matrix
animal_1982_matrix <- read.csv(here('data', 'clean', '20220128_animal_matrix_1982-1995.csv'), row.names = 1)
animal_1996_matrix <- read.csv(here('data', 'clean', '20220128_animal_matrix_1996-2006.csv'), row.names = 1)
animal_2011_matrix <- read.csv(here('data', 'clean', '20220128_animal_matrix_2011-end.csv'), row.names = 1)
# algae matrix
algae_1982_matrix <- read.csv(here('data', 'clean', '20220128_algae_matrix_1982-1995.csv'), row.names = 1)
algae_1996_matrix <- read.csv(here('data', 'clean', '20220128_algae_matrix_1996-2006.csv'), row.names = 1)
algae_2011_matrix <- read.csv(here('data', 'clean', '20220128_algae_matrix_2011-end.csv'), row.names = 1)
```

setup
```{r}
#define options for heirarchical clustering 
methodsClust <- c("single", "complete", "average")


# generate groups to color tsnes, from taxonomy
#update this, it won't work
animal_phyla <- trait_raw %>%
  subset(group %in% c('Invertebrate', 'Vertebrate')) %>%
  dplyr:::select(species, phylum)

animal_phyla <- animal_phyla %>%
  subset(species %in% sp_list$value)
```



# Animals


Here you will use the number of clusters identified above, as well as the method

## 1982-1995

### dendrogram

```{r}

animal_1982_dist <- as.dist(animal_1982_matrix)

######Animals
animal_1982_fit <- hclust(animal_1982_dist, method = 'average')  #change cluster method
animal_1982_clust <- cutree(animal_1982_fit, 4)  # change number of clusters

animal_1982_dendr <- dendro_data(animal_1982_fit, type="rectangle") 

animal_1982_labs <- label(animal_1982_dendr)
animal_1982_labs$cluster <- as.factor(animal_1982_clust)
  
animal_1982_dendr_plot <- ggplot() +
  geom_segment(data=segment(animal_1982_dendr), aes(x=x, y=y, xend=xend, yend=yend)) +
  geom_text(data=animal_1982_labs, aes(x=x, y=y, label=label, hjust=0, color = cluster), size=2) +
  coord_flip() + scale_y_reverse(expand=c(0.1, 0), limits = c(.9,-0.1)) +
  theme_void()
  

animal_1982_dendr_plot

ggsave(here('output', 'cluster_ks', '20220128_timeseries',
            'animal-cluster-dendro-1982.png'), plot = last_plot())

# also make csv lists of animals in those years
animal_1982_clust_l <- animal_1982_labs %>%
  select(label, cluster)

write.csv(animal_1982_clust_l, here('output', 'cluster_ks', '20220128_timeseries',
                               'animal-clusters-1982-1995.csv'))
```

### tsne

```{r}
## animals


tsne_obj_an <- Rtsne(animal_1982_matrix, is_distance = TRUE, perplexity = 5)
#plot(tsne_obj_an$Y) # black and white plain dots

#add anything you want to map to the tsne to this object
tsne_plot_an <- data.frame(x = tsne_obj_an$Y[,1], y = tsne_obj_an$Y[,2], 
                         animal_1982, animal_clust_l)

tsne_1982_animal <- ggplot(tsne_plot_an, aes(x=x, y=y)) + 
  #geom_point(aes(color = common_name_division_bgr)) +
  #geom_point(aes(color = phylum)) +
  geom_point(aes(color = cluster)) +
  theme_classic()

tsne_1982_animal

ggsave(here('output', 'cluster_ks', '20220128_timeseries',
            'animal-cluster-tsne_1982r-phy.png'), plot = last_plot())

```


## 1982-1995

### dendrogram

```{r}

animal_1996_dist <- as.dist(animal_1996_matrix)

######Animals
animal_1996_fit <- hclust(animal_1996_dist, method = 'average')  #change cluster method
animal_1996_clust <- cutree(animal_1996_fit, 4)  # change number of clusters

animal_1996_dendr <- dendro_data(animal_1996_fit, type="rectangle") 

animal_1996_labs <- label(animal_1996_dendr)
animal_1996_labs$cluster <- as.factor(animal_1996_clust)
  
animal_1996_dendr_plot <- ggplot() +
  geom_segment(data=segment(animal_1996_dendr), aes(x=x, y=y, xend=xend, yend=yend)) +
  geom_text(data=animal_1996_labs, aes(x=x, y=y, label=label, hjust=0, color = cluster), size=2) +
  coord_flip() + scale_y_reverse(expand=c(0.1, 0), limits = c(.9,-0.1)) +
  theme_void()
  

animal_1996_dendr_plot

ggsave(here('output', 'cluster_ks', '20220128_timeseries',
            'animal-cluster-dendro-1996.png'), plot = last_plot())

# also make csv lists of animals in those years
animal_1996_clust_l <- animal_1996_labs %>%
  select(label, cluster)

write.csv(animal_1996_clust_l, here('output', 'cluster_ks', '20220128_timeseries',
                               'animal-clusters-1996-2006.csv'))
```

### tsne

```{r}
## animals


tsne_obj_an <- Rtsne(animal_1996_matrix, is_distance = TRUE, perplexity = 5)
#plot(tsne_obj_an$Y) # black and white plain dots

#add anything you want to map to the tsne to this object
tsne_plot_an <- data.frame(x = tsne_obj_an$Y[,1], y = tsne_obj_an$Y[,2], 
                         animal_1996, animal_1996_clust_l)

tsne_1996_animal <- ggplot(tsne_plot_an, aes(x=x, y=y)) + 
  #geom_point(aes(color = common_name_division_bgr)) +
  #geom_point(aes(color = phylum)) +
  geom_point(aes(color = cluster)) +
  theme_classic()

tsne_1996_animal

ggsave(here('output', 'cluster_ks', '20220128_timeseries',
            'animal-cluster-tsne_1996-cluster.png'), plot = last_plot())

```





# Algae


## 1982-1995

### dendrogram

```{r}

algae_1982_dist <- as.dist(algae_1982_matrix)

######algaes
algae_1982_fit <- hclust(algae_1982_dist, method = 'average')  #change cluster method
algae_1982_clust <- cutree(algae_1982_fit, 4)  # change number of clusters

algae_1982_dendr <- dendro_data(algae_1982_fit, type="rectangle") 

algae_1982_labs <- label(algae_1982_dendr)
algae_1982_labs$cluster <- as.factor(algae_1982_clust)
  
algae_1982_dendr_plot <- ggplot() +
  geom_segment(data=segment(algae_1982_dendr), aes(x=x, y=y, xend=xend, yend=yend)) +
  geom_text(data=algae_1982_labs, aes(x=x, y=y, label=label, hjust=0, color = cluster), size=2) +
  coord_flip() + scale_y_reverse(expand=c(0.1, 0), limits = c(.9,-0.1)) +
  theme_void()
  

algae_1982_dendr_plot

ggsave(here('output', 'cluster_ks', '20220128_timeseries',
            'algae-cluster-dendro-1982.png'), plot = last_plot())

# also make csv lists of algaes in those years
algae_1982_clust_l <- algae_1982_labs %>%
  select(label, cluster)

write.csv(algae_1982_clust_l, here('output', 'cluster_ks', '20220128_timeseries',
                               'algae-clusters-1982-1995.csv'))
```

### tsne

```{r}
## algaes


tsne_obj_an <- Rtsne(algae_1982_matrix, is_distance = TRUE, perplexity = 5)
#plot(tsne_obj_an$Y) # black and white plain dots

#add anything you want to map to the tsne to this object
tsne_plot_an <- data.frame(x = tsne_obj_an$Y[,1], y = tsne_obj_an$Y[,2], 
                         algae_1982, algae_1982_clust_l)

tsne_1982_algae <- ggplot(tsne_plot_an, aes(x=x, y=y)) + 
  #geom_point(aes(color = common_name_division_bgr)) +
  #geom_point(aes(color = phylum)) +
  geom_point(aes(color = cluster)) +
  theme_classic()

tsne_1982_algae

ggsave(here('output', 'cluster_ks', '20220128_timeseries',
            'algae-cluster-tsne_1982r-phy.png'), plot = last_plot())

```