---
title: "traits+years"
author: "Kate Sheridan"
date: "1/28/2022"
output: html_document
---
# Add trait data
This script adds trait data to the species lists from the filter, replaces the species in the list with groups determined for traits, and also makes a master trait x year/transect/position list.

```{r setup, include=FALSE}
library(dplyr)
library(stringr)
library(here)

# here filepaths
trait <- here('data','clean')
field <- here('data','fielddata')
```


```{r}
#load in imputed data
## remove first column, turn all into factors
animal_imp2 <- read.csv(file = here(trait,'20220321_animal_imputed.csv'))[,-1]%>% 
  mutate(across(.fns = ~ as.factor(.)))
algae_imp2 <- read.csv(file = here(trait,'20220525_algae_imputed.csv'))[,-1]%>% 
  mutate(across(.fns = ~ as.factor(.)))

# combined year+transect list
## read in formatted that can play with the others
pc_ct <- read.csv(file = here(field, 'combined_intertidal_species.csv')) %>%
  janitor::clean_names() %>%
  rename(species = organism)

# for time series
sp_1982r <- read.csv(here('data', 'fielddata', 'sp_1982-1995.csv')) %>%
  select(value) %>%
  dplyr::rename(species = value)
sp_1996r <- read.csv(here('data', 'fielddata', 'sp_1996-2006.csv')) %>%
  select(value) %>%
  dplyr::rename(species = value)
sp_2011r <- read.csv(here('data', 'fielddata', 'sp_2011-end.csv')) %>%
  select(value) %>%
  dplyr::rename(species = value)

# group key, make named list
sp_key <- read_csv((here('data', 'splists', 'species_group_key.csv'))) %>%
  filter(!(is.na(Replacement)))

sp_key2 <- setNames(as.list(sp_key$Species), sp_key$Replacement)
sp_key2 <- unlist(sp_key2)

```

```{r combined}
# update taxonomy

pc_ct$species2 <- sapply(pc_ct$species, function(species) {
  names(sp_key2)[sp_key2 == species]
})

# this makes up for that real quick and easy
pc_ct <- pc_ct %>%
  mutate(species2 = str_replace_all(species2, c("character\\(0\\)" = ""))) %>%
  na_if("") %>%
  mutate(species3 = coalesce(c(species2), c(species))) %>%
  select(!(c(species,species2))) %>%
  dplyr::rename(species = species3) %>%
  distinct()


pc_ct_animal <- pc_ct %>%
  left_join(animal_imp2) %>%
  filter(!(is.na(phylum)))
pc_ct_algae <- pc_ct %>%
  left_join(algae_imp2) %>%
  filter(!(is.na(group)))

write.csv(pc_ct_animal, here(trait, '20220321_1982-end_animal.csv'), row.names = FALSE)
write.csv(pc_ct_algae, here(trait, '20220525_1982-end_algae.csv'), row.names = FALSE)


```



```{r 1982}
# update taxonomy

sp_1982r$species2 <- sapply(sp_1982r$species, function(species) {
  names(sp_key2)[sp_key2 == species]
})

# this makes up for that real quick and easy
sp_1982r <- sp_1982r %>%
  mutate(species2 = str_replace_all(species2, c("character\\(0\\)" = ""))) %>%
  na_if("") %>%
  mutate(species3 = coalesce(c(species2), c(species))) %>%
  select(species3) %>%
  dplyr::rename(species = species3) %>%
  distinct()


sp_1982r_animal <- sp_1982r %>%
  left_join(animal_imp2)# %>%
  #filter(!(is.na(group)))
sp_1982r_algae <- sp_1982r %>%
  left_join(algae_imp2) %>%
  filter(!(is.na(group)))

write.csv(sp_1982r_animal, here('data', 'clean', '20220323_1982-1995_animal.csv'), row.names = FALSE)
write.csv(sp_1982r_algae, here('data', 'clean', '20220525_1982-1995_algae.csv'), row.names = FALSE)
```

```{r 1996}
sp_1996r$species2 <- sapply(sp_1996r$species, function(species) {
  names(sp_key2)[sp_key2 == species]
})

# this makes up for that real quick and easy
sp_1996r <- sp_1996r %>%
  mutate(species2 = str_replace_all(species2, c("character\\(0\\)" = ""))) %>%
  na_if("") %>%
  mutate(species3 = coalesce(c(species2), c(species))) %>%
  select(species3) %>%
  dplyr::rename(species = species3) %>%
  distinct()


sp_1996r_animal <- sp_1996r %>%
  left_join(animal_imp2)# %>%
 # filter(!(is.na(group)))
sp_1996r_algae <- sp_1996r %>%
  left_join(algae_imp2) %>%
  filter(!(is.na(group)))

write.csv(sp_1996r_animal, here('data', 'clean', '20220323_1996-2006_animal.csv'), row.names = FALSE)
write.csv(sp_1996r_algae, here('data', 'clean', '20220323_1996-2006_algae.csv'), row.names = FALSE)
```


```{r}
sp_2011r$species2 <- sapply(sp_2011r$species, function(species) {
  names(sp_key2)[sp_key2 == species]
})

# this makes up for that real quick and easy
sp_2011r <- sp_2011r %>%
  mutate(species2 = str_replace_all(species2, c("character\\(0\\)" = ""))) %>%
  na_if("") %>%
  mutate(species3 = coalesce(c(species2), c(species))) %>%
  select(species3) %>%
  dplyr::rename(species = species3) %>%
  distinct()


sp_2011r_animal <- sp_2011r %>%
  left_join(animal_imp2) #%>%
  #filter(!(is.na(group)))
sp_2011r_algae <- sp_2011r %>%
  left_join(algae_imp2) %>%
  filter(!(is.na(group)))

write.csv(sp_2011r_animal, here('data', 'clean', '20220313_2011-end_animal.csv'), row.names = FALSE)
write.csv(sp_2011r_algae, here('data', 'clean', '20220525_2011-end_algae.csv'), row.names = FALSE)
```

