---
title: "ks_mca-hcpc_timeseries"
author: "Kate Sheridan"
date: "3/13/2022"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(ggplot2)
library(FactoMineR)
library(factoextra)
library(dplyr)
library(here)

# here filepaths
mcadata <- here('data', 'clean')
plots <- here('output', '2022march', 'mca')
```

## load in data

```{r}
# all species
algae_imputed_all <- read_csv(here(mcadata, "20220312_algae_imputed.csv"),
                                 col_select = !1) %>%
  filter(intertidal == 'yes') %>%
  select(!(c(body_size_avg_bin, intertidal,
             calcareous)))

animal_imputed_all <- read_csv(here(mcadata, "20220312_animal_imputed.csv"),
                                 col_select = !1) %>%
  filter(intertidal == 'yes') %>%
  select(!(c(intertidal)))

# time series
algae_traits <- read_csv(here(mcadata, "20220314_1982-end_algae.csv")) %>%
  filter(intertidal == 'yes') %>%
  select(!(c(intertidal)))

animal_traits <- read_csv(here(mcadata, "20220314_1982-end_animal.csv")) %>%
  filter(intertidal == 'yes') %>%
  select(!(c(intertidal)))


animal_1982_1995_traits <- read_csv(here(mcadata, "20220313_1982-1995_animal.csv")) %>%
  filter(intertidal == 'yes') %>%
  select(!(c(intertidal)))
animal_2011_end_traits <- read_csv(here(mcadata, "20220313_2011-end_animal.csv")) %>%
  filter(intertidal == 'yes') %>%
  select(!(c(intertidal)))
```


## load in functions

```{r}
# input should be imputed traits, filtered as needed
## note that we're selecting columns automatically here 
## starting with column 3 after the species column; change if not true
# note that only output starting with gg are ggplot objects
appledoreMCAHCPC <- function(traits) {
  # select columns for MCA
  traits <- traits %>% 
    column_to_rownames('species') %>%
    dplyr::select(3:(ncol(traits)-1)) %>%
    mutate(across(.fns = ~ as.factor(.)))
  # run MCA
  mca2 <- MCA(traits, graph = FALSE)
  # prepare data for plotting
  cats=apply(traits, 2, function(x) nlevels(as.factor(x)))
  mca2_vars_df = data.frame(mca2$var$coord, Variable = rep(names(cats), 
                                                         cats))
  mca2_obs_df = data.frame(mca2$ind$coord)
  # plot with lines and vectors
  mcaggplot <- ggplot(data = mca2_obs_df, aes(x = Dim.1, y = Dim.2)) + 
    geom_hline(yintercept = 0, colour = "gray70") + 
    geom_vline(xintercept = 0, colour = "gray70") + 
    geom_point(colour = "gray50", alpha = 0.7) + 
    geom_density2d(colour = "gray80") + 
    geom_text(data = mca2_vars_df, aes(x = Dim.1, y = Dim.2, 
                                     label = rownames(mca2_vars_df), 
                                     colour = Variable)) + 
    ggtitle("MCA plot with FactorMineR") + 
    scale_colour_discrete(name = "Variable") +
    geom_segment(data = mca2_vars_df, aes(x = 0, y = 0, xend = Dim.1, yend = Dim.2), 
               arrow = arrow(length = unit(0.2, "cm")), colour = "black") +
    theme_bw(20)+ xlab ("Dim 1 21.28 %")+ ylab("Dim 2 17.54%")
  # ellipses plot
  plot_ellipses <- plotellipses(mca2)
  # screeplot
  scree2 <- fviz_screeplot(mca2)
  contrib2 <- fviz_contrib(mca2, choice = "var", axes = 1:2, top = 15)
  
  
  # run HCPC
  hcpc2 <- HCPC(mca2, graph = FALSE)
  # hcpc dendrogram
  hcpc_dend <- fviz_dend(hcpc2)
  # hcpc factor map
  hcpc_clust <- fviz_cluster(hcpc2, geom = "point", main = "Factor map")
  
  
  #output
  list(mcaeigen = mca2$eig, mcavar = mca2$var,
       mcaind = mca2$ind,
       clustmembers = hcpc2$desc.ind$para,
       clustervariables = hcpc2$desc.var$category,
       mcaplotraw = plot(mca2), ggmca = mcaggplot,
       ggscreeplot = scree2, ggcontrib = contrib2,
       ellipses = plot_ellipses, ggdendrogram = hcpc_dend,
       ggclusterplot = hcpc_clust)
}
```

## run function

```{r}
algae_all <- appledoreMCAHCPC(algae_imputed_all)

animal_all <- appledoreMCAHCPC(animal_imputed_all)

animal_1982_1995 <- appledoreMCAHCPC(animal_1982_1995_traits)
animal_2011_end <- appledoreMCAHCPC(animal_2011_end_traits)
```
explore output; use df$ to see all saved plots and summary stats
Any output starting with gg is a ggplot object and can be chained with ggplot functions such as:
`algae_all$ggmca + theme_bw()`
```{r}
# example view a summary
algae_all$mcaeigen

# example ggplot
animal_all$ggscreeplot + theme_bw()

animal_all$ggdendrogram

animal_1982_1995$ggdendrogram
animal_2011_end$ggdendrogram
```


