---
title: "ks_mca_clusters"
author: "Kate Sheridan"
date: "3/11/2022"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(ggplot2)
library(FactoMineR)
library(factoextra)
library(dplyr)
library(here)

# here filepaths
mcadata <- here('data', 'clean')
plots <- here('output', '2022march', 'mca')
```

load in functions
```{r}
# input should be imputed traits, filtered as needed
## note that we're selecting columns automatically here 
## starting with column 3 after the species column; change if not true
# note that only output starting with gg are ggplot objects
appledoreMCAHCPC <- function(traits) {
  # select columns for MCA
  traits <- traits %>% 
    column_to_rownames('species') %>%
    dplyr::select(3:(ncol(traits)-1)) %>%
    mutate(across(.fns = ~ as.factor(.)))
  # run MCA
  mca2 <- MCA(traits, graph = FALSE)
  # prepare data for plotting
  cats=apply(traits, 2, function(x) nlevels(as.factor(x)))
  mca2_vars_df = data.frame(mca2$var$coord, Variable = rep(names(cats), 
                                                         cats))
  mca2_obs_df = data.frame(mca2$ind$coord)
  # plot with lines and vectors
  mcaggplot <- ggplot(data = mca2_obs_df, aes(x = Dim.1, y = Dim.2)) + 
    geom_hline(yintercept = 0, colour = "gray70") + 
    geom_vline(xintercept = 0, colour = "gray70") + 
    geom_point(colour = "gray50", alpha = 0.7) + 
    geom_density2d(colour = "gray80") + 
    geom_text(data = mca2_vars_df, aes(x = Dim.1, y = Dim.2, 
                                     label = rownames(mca2_vars_df), 
                                     colour = Variable)) + 
    ggtitle("MCA plot with FactorMineR") + 
    scale_colour_discrete(name = "Variable") +
    geom_segment(data = mca2_vars_df, aes(x = 0, y = 0, xend = Dim.1, yend = Dim.2), 
               arrow = arrow(length = unit(0.2, "cm")), colour = "black") +
    theme_bw(20)+ xlab ("Dim 1 21.28 %")+ ylab("Dim 2 17.54%")
  # ellipses plot
  plot_ellipses <- plotellipses(mca2)
  # screeplot
  scree2 <- fviz_screeplot(mca2)
  contrib2 <- fviz_contrib(mca2, choice = "var", axes = 1:2, top = 15)
  
  
  # run HCPC
  hcpc2 <- HCPC(mca2, graph = FALSE)
  # hcpc dendrogram
  hcpc_dend <- fviz_dend(hcpc2)
  # hcpc factor map
  hcpc_clust <- fviz_cluster(hcpc2, geom = "point", main = "Factor map")
  
  
  #output
  list(mcaeigen = mca2$eig, mcavar = mca2$var,
       mcaind = mca2$ind,
       clustmembers = hcpc2$desc.ind$para,
       clustervariables = hcpc2$desc.var$category,
       mcaplotraw = plot(mca2), ggmca = mcaggplot,
       ggscreeplot = scree2, ggcontrib = contrib2,
       ellipses = plot_ellipses, ggdendrogram = hcpc_dend,
       ggclusterplot = hcpc_clust)
}



testalgae <- appledoreMCAHCPC(traits_algae_imputed)

testalgae$ggmca + theme_bw()
testalgae$ggcontrib + theme_bw()
testalgae$summarymca

testalgae$mcaind


testanimal <- appledoreMCAHCPC(traits_animal_imputed)

testanimal$mcaind

testanimal$ggmca
testanimal$dendrogram
```


# Run MCAs
## Algae
### All
```{r load-algae-all}
traits_algae_imputed <- read_csv(here(mcadata, "20220312_algae_imputed.csv"),
                                 col_select = !1) %>%
  filter(intertidal == 'yes') %>%
  select(!(c(body_size_avg_bin, intertidal,
             calcareous)))

#glimpse(traits_algae_imputed)
```

```{r mca-algae-all}
traits_algae_imputed_sel<-traits_algae_imputed[,4:ncol(traits_algae_imputed)] #select columns of interest

# to factors
traits_algae_imputed_sel <- traits_algae_imputed_sel %>%
  mutate(across(.fns = ~ as.factor(.)))

#MCA
mca2 = MCA(traits_algae_imputed_sel, graph = TRUE)
summary (mca2)
mca2$eig
mca2$var
mca2$ind

variables_scores_algae<-mca2$var$eta2 
#str(variables_scores_algae) 
head(mca2$var$coord)
#mca2
plot(mca2)
```

```{r mca-plot-algae-all}
# prep data for plot
cats=apply(traits_algae_imputed_sel, 2, function(x) nlevels(as.factor(x)))

mca2_vars_df = data.frame(mca2$var$coord, Variable = rep(names(cats), 
                                                         cats))
mca2_obs_df = data.frame(mca2$ind$coord)

# plot of variable categories
ggplot(data = mca2_vars_df, aes(x = Dim.1, y = Dim.2, label = rownames(mca2_vars_df))) + 
  geom_hline(yintercept = 0, colour = "gray70") + 
  geom_vline(xintercept = 0, colour = "gray70") + 
  geom_text(aes(colour = Variable)) + 
  ggtitle("Algae_MCA plot of variables using R package FactoMineR")

# MCA plot of observations and categories [Plot used for the presentation!]
plot_algae_1982_1995<-ggplot(data = mca2_obs_df, aes(x = Dim.1, y = Dim.2)) + 
  geom_hline(yintercept = 0, colour = "gray70") + 
  geom_vline(xintercept = 0, colour = "gray70") + 
  geom_point(colour = "gray50", alpha = 0.7) + 
  geom_density2d(colour = "gray80") + 
  geom_text(data = mca2_vars_df, aes(x = Dim.1, y = Dim.2, 
                                     label = rownames(mca2_vars_df), 
                                     colour = Variable)) + 
  ggtitle("Algae, MCA plot 1982_1995. FactorMineR") + 
  scale_colour_discrete(name = "Variable") +
  geom_segment(data = mca2_vars_df, aes(x = 0, y = 0, xend = Dim.1, yend = Dim.2), 
               arrow = arrow(length = unit(0.2, "cm")), colour = "black") +
  theme_bw(20)+ xlab ("Dim 1 21.28 %")+ ylab("Dim 2 17.54%")

plot_algae_1982_1995
ggsave(here(plots, '20220312_mca_algae-all.png'), plot = plot_algae_1982_1995,
       device = 'png', width = 10)

# ellipses plot
plot_ellipses_algae_1982_1995 <- plotellipses(mca2,keepvar=c(2:11))

# saving these requires the png/dev.off combo. 
## check how to adjust output later
png(here(plots, '20220312_mca_ellipse_algae-all.png'))
plot_ellipses_algae_1982_1995
dev.off()
```

```{r}
algae_all_hcpc <- HCPC(mca2, graph = FALSE)

# Dendrogram
fviz_dend(algae_all_hcpc, show_labels = FALSE)
# Individuals facor map
fviz_cluster(algae_all_hcpc, geom = "point", main = "Factor map")

# shows each cluster and lists variables that define it in order
algae_all_hcpc$desc.var$category

#shows individuals
algae_all_hcpc$desc.ind$para


png(here(plots, '20220312_mca_cluster-tree_algae-all.png'))
fviz_dend(algae_all_hcpc, show_labels = FALSE)
dev.off()

png(here(plots, '20220312_mca_cluster-map_algae-all.png'))
fviz_cluster(algae_all_hcpc, geom = "point", main = "Factor map")
dev.off()

```





### Year chunks

## Animals

```{r}
traits_animal_imputed <- read_csv(here(mcadata, "20220312_animal_imputed.csv"),
                                 col_select = !1) %>%
  filter(intertidal == 'yes') %>%
  select(!(c(body_size_avg_bin, intertidal)))
```
```{r animal-mca}
traits_animal_imputed_sel<-traits_animal_imputed[,4:ncol(traits_animal_imputed)] #select columns of interest

# to factors
traits_animal_imputed_sel <- traits_animal_imputed_sel %>%
  mutate(across(.fns = ~ as.factor(.)))

#MCA
mca3 = MCA(traits_animal_imputed_sel, graph = TRUE)
```



```{r mca-plot-algae-all}
# prep data for plot
mca3_vars_df = data.frame(mca3$var$coord, Variable = rep(names(cats), 
                                                         cats))
mca3_obs_df = data.frame(mca3$ind$coord)

# plot of variable categories
ggplot(data = mca3_vars_df, aes(x = Dim.1, y = Dim.2, label = rownames(mca3_vars_df))) + 
  geom_hline(yintercept = 0, colour = "gray70") + 
  geom_vline(xintercept = 0, colour = "gray70") + 
  geom_text(aes(colour = Variable)) + 
  ggtitle("Animal_MCA plot of variables using R package FactoMineR")

# MCA plot of observations and categories [Plot used for the presentation!]
plot_animal_1982_end <-ggplot(data = mca3_obs_df, aes(x = Dim.1, y = Dim.2)) + 
  geom_hline(yintercept = 0, colour = "gray70") + 
  geom_vline(xintercept = 0, colour = "gray70") + 
  geom_point(colour = "gray50", alpha = 0.7) + 
  geom_density2d(colour = "gray80") + 
  geom_text(data = mca3_vars_df, aes(x = Dim.1, y = Dim.2, 
                                     label = rownames(mca3_vars_df), 
                                     colour = Variable)) + 
  ggtitle("Animal, MCA plot 1982_end. FactorMineR") + 
  scale_colour_discrete(name = "Variable") +
  geom_segment(data = mca3_vars_df, aes(x = 0, y = 0, xend = Dim.1, yend = Dim.2), 
               arrow = arrow(length = unit(0.2, "cm")), colour = "black") +
  theme_bw(20)+ xlab ("Dim 1 21.28 %")+ ylab("Dim 2 17.54%")

plot_animal_1982_end
ggsave(here(plots, '20220313_mca_animal-all.png'), plot = plot_algae_1982_1995,
       device = 'png', width = 10)

# ellipses plot
plot_ellipses_animal_1982_end <- plotellipses(mca3,keepvar=c(2:11))

# saving these requires the png/dev.off combo. 
## check how to adjust output later
png(here(plots, '20220313_mca_ellipse_animal-all.png'))
plot_ellipses_animal_1982_end
dev.off()
```


```{r}
animal_all_hcpc <- HCPC(mca3, graph = FALSE)

# Dendrogram
fviz_dend(animal_all_hcpc, show_labels = FALSE)
# Individuals facor map
fviz_cluster(animal_all_hcpc, geom = "point", main = "Factor map")

# shows each cluster and lists variables that define it in order
animal_all_hcpc$desc.var$category


png(here(plots, '20220313_mca_cluster-tree_animal-all.png'))
fviz_dend(animal_all_hcpc, show_labels = FALSE)
dev.off()

png(here(plots, '20220313_mca_cluster-map_animal-all.png'))
fviz_cluster(animal_all_hcpc, geom = "point", main = "Factor map")
dev.off()
```

