---
title: "traits+years"
author: "Kate Sheridan"
date: "1/28/2022"
output: html_document
---

```{r setup, include=FALSE}
library(dplyr)
library(here)
```


```{r}
#load in imputed data
animal_imp2 <- read.csv(file = here('data', 'clean','20220117_animal_imputed.csv'))
algae_imp2 <- read.csv(file = here('data', 'clean','20220117_algae_imputed.csv'))

#remove x column
animal_imp2 <- animal_imp2[,2:ncol(animal_imp2),]
algae_imp2 <- algae_imp2[,2:ncol(algae_imp2),]

#make factors
animal_imp2 <- animal_imp2 %>% 
  mutate(across(.fns = ~ as.factor(.)))
algae_imp2 <- algae_imp2 %>% 
  mutate(across(.fns = ~ as.factor(.)))

#uncomment the one you need
sp_1982r <- read.csv(here('data', 'fielddata', 'sp_1982-1995.csv')) %>%
  select(value) %>%
  rename(species = value)
sp_1996r <- read.csv(here('data', 'fielddata', 'sp_1996-2006.csv')) %>%
  select(value) %>%
  rename(species = value)
sp_2011r <- read.csv(here('data', 'fielddata', 'sp_2011-end.csv')) %>%
  select(value) %>%
  rename(species = value)

# group key
sp_key <- read.csv((here('data', 'splists', 'species_group_key.csv'))) %>%
  filter(!(is.na(Replacement)))

sp_key2 <- setNames(as.list(sp_key$Species), sp_key$Replacement)
sp_key2 <- unlist(sp_key2)


```


```{r 1982}
# update taxonomy

sp_1982r$species2 <- sapply(sp_1982r$species, function(species) {
  names(sp_key2)[sp_key2 == species]
})

# this makes up for that real quick and easy
sp_1982r <- sp_1982r %>%
  mutate(species2 = str_replace_all(species2, c("character\\(0\\)" = ""))) %>%
  na_if("") %>%
  mutate(species3 = coalesce(c(species2), c(species))) %>%
  select(species3) %>%
  rename(species = species3) %>%
  distinct()


sp_1982r_animal <- sp_1982r %>%
  full_join(animal_imp2) %>%
  filter(!(is.na(group)))
sp_1982r_algae <- sp_1982r %>%
  full_join(algae_imp2) %>%
  filter(!(is.na(group)))

write.csv(sp_1982r_animal, here('data', 'clean', '20220128_1982-1995_animal.csv'))
write.csv(sp_1982r_algae, here('data', 'clean', '20220128_1982-1995_algae.csv'))
```

```{r 1996}
sp_1996r$species2 <- sapply(sp_1996r$species, function(species) {
  names(sp_key2)[sp_key2 == species]
})

# this makes up for that real quick and easy
sp_1996r <- sp_1996r %>%
  mutate(species2 = str_replace_all(species2, c("character\\(0\\)" = ""))) %>%
  na_if("") %>%
  mutate(species3 = coalesce(c(species2), c(species))) %>%
  select(species3) %>%
  rename(species = species3) %>%
  distinct()


sp_1996r_animal <- sp_1996r %>%
  full_join(animal_imp2) %>%
  filter(!(is.na(group)))
sp_1996r_algae <- sp_1996r %>%
  full_join(algae_imp2) %>%
  filter(!(is.na(group)))

write.csv(sp_1982r_animal, here('data', 'clean', '20220128_1996-2006_animal.csv'))
write.csv(sp_1996r_algae, here('data', 'clean', '20220128_1996-2006_algae.csv'))
```


```{r}

sp_2011r$species2 <- sapply(sp_2011r$species, function(species) {
  names(sp_key2)[sp_key2 == species]
})

# this makes up for that real quick and easy
sp_2011r <- sp_2011r %>%
  mutate(species2 = str_replace_all(species2, c("character\\(0\\)" = ""))) %>%
  na_if("") %>%
  mutate(species3 = coalesce(c(species2), c(species))) %>%
  select(species3) %>%
  rename(species = species3) %>%
  distinct()


sp_2011r_animal <- sp_2011r %>%
  full_join(animal_imp2) %>%
  filter(!(is.na(group)))
sp_2011r_algae <- sp_2011r %>%
  full_join(algae_imp2) %>%
  filter(!(is.na(group)))

write.csv(sp_2011r_animal, here('data', 'clean', '20220128_2011-end_animal.csv'))
write.csv(sp_2011r_algae, here('data', 'clean', '20220128_2011-end_algae.csv'))
```

