---
title: "trait_clustering"
output: html_document
---

Setup
```{r setup, include=FALSE}
library('nomclust')
library('tidyverse')
library('mice')
library('cluster')
library(nomclust) 
library(ggplot2)
library(reshape)
library(ggthemes)
library(fpc)
library(gridExtra)
library(tidyverse)
library(here)
library(Rtsne)
library(gclus)
library(vegan)
library(ggdendro)
library(tsne)
library(stringr)
library(ggfortify)
```

Load in data
```{r load-in}
#be sure to use na.strings or imputation will fail!
trait_raw <- read.csv(here("data", '20210730_ShoalsFunctionalTraits.csv'), na.strings = c("","NA", 'N/A'))
```

Ladds et al 2018
- must have a complete dataset
- continuous variables must be discretized
Their repository: https://github.com/MoniqueLadds/FunctionalGroupClassification

Step 1, data prep and imputation

Filtering relevant traits for imputation only
```{r filter}
algae_raw <- trait_raw %>%
  subset(group == 'Algae') %>%
    dplyr:::select(species, group, common_name_division_bgr,
                   turf_subcanopy_canopy_algae, Steneck_Dethier_morphology_algae, 
                   body_size_avg_bin, morphology1, benthic, epibiotic,
                   #epiphytic, epizoic, epifaunal, epilithic, 
                   #invasive, 
                 intertidal, subtidal)

animal_raw <- trait_raw %>%
  subset(group %in% c('Invertebrate', 'Vertebrate')) %>%
  dplyr:::select(species, group, common_name_division_bgr, body_size_avg_bin,
                 morphology1, dietary_pref_c, trophic_level, motility_juv,
                 motility_adult, benthic, epibiotic,
                 #epiphytic, epizoic, epifaunal, epilithic, 
                 invasive, intertidal, subtidal)

glimpse(algae_raw)
glimpse(animal_raw)

# DATA CLEANING #
# all columns are character, must be factor.
algae_clean <- algae_raw %>% 
  mutate(Steneck_Dethier_morphology_algae = replace(Steneck_Dethier_morphology_algae, 
                                                    Steneck_Dethier_morphology_algae == 'corticated macrophytes',
                                                    'corticated macrophyte')) %>% 
  mutate(across(.fns = ~ as.factor(.)))
# motility_adult has a "both" in there that should probably be fixed
animal_clean <- animal_raw %>% 
  mutate(trophic_level = str_trim(trophic_level),
         invasive = replace(invasive, invasive == 'no?', 'no'),
         invasive = replace(invasive, invasive == 'yes (controversial)', 'yes')) %>% 
  mutate(across(.fns = ~ as.factor(.)))
# write_csv(algae_clean, "../data/algae_clean.csv")
# write_csv(animal_clean, '../data/animal_clean.csv')
```


```{r}

algae_imp <- mice(algae_clean[,3:ncol(algae_clean)], m=5, method = 'logreg', print = F)
algae_imp2 <- complete(algae_imp) #action
algae_imp2 <- cbind(algae_raw[,1:2],algae_imp2)

#save(algae_imp2, file = here('data','algae_imputed.RData'))
write.csv(algae_imp2, file = here('data', 'clean','algae_imputed.csv'))

#to see logged events
algae_imp$loggedEvents



animal_imp <- mice(animal_clean[,3:ncol(animal_clean)], m=5, method = 'polyreg', print = F)
animal_imp2 <- complete(animal_imp) #action
animal_imp2 <- cbind(animal_raw[,1:2],animal_imp2)

#save(animal_imp2, file = here('data','animals_imputed.RData'))
write.csv(animal_imp2, file = here('data', 'clean','animal_imputed.csv'))

#to see logged events
animal_imp$loggedEvents
```



Step 2 Distance Matrix

```{r}
#set up evaluations

##list of the possible internal validation measures
nomclustEvals <- c("WCM", "WCE", "PSTau", "PSU", "PSFM", "PSFE")
#List of the possible linkage methods
clusterMethod <- c("average", "complete", "single")


#Colours for the different distance matrices
group.colours <- c("Goodall" = "black",
                   "Goodall_2" = "#CCCCCC",
                   "Goodall_3" = "#999999",
                   "Goodall_4" = "#666666",
                   "Eskin"="blue",
                   "IOF"="orange", 
                   "OF" = "#D55E00",
                   "Lin"="purple",
                   "Lin_1" = "#9999CC",
                   "Simple matching"="darkgreen")

subDist <- c("Goodall","Eskin", "IOF", "Lin", "Simple matching")

#relevant functions from Ladds 2018
fit_nomclust <- function(distanceMethod,clusterMethod)
                        {nomclust(dataSET, measure = distanceMethod, 
                                           method = clusterMethod)}

```


```{r dissimilarity matrix legendre}
"coldiss" <- function(D, nc = 4, byrank = TRUE, diag = FALSE)
{
	require(gclus)

	if (max(D)>1) D <- D/max(D)

	if (byrank) {
		spe.color = dmat.color(1-D, cm.colors(nc))
	}
	else {
		spe.color = dmat.color(1-D, byrank=FALSE, cm.colors(nc))
	}

	spe.o = order.single(1-D)
	speo.color = spe.color[spe.o,spe.o]
	
	op = par(mfrow=c(1,2), pty="s")

	if (diag) {
		plotcolors(spe.color, rlabels=attributes(D)$Labels, 
			main="Dissimilarity Matrix", 
			dlabels=attributes(D)$Labels)
		plotcolors(speo.color, rlabels=attributes(D)$Labels[spe.o], 
			main="Ordered Dissimilarity Matrix", 
			dlabels=attributes(D)$Labels[spe.o])
	}
	else {
		plotcolors(spe.color, rlabels=attributes(D)$Labels, 
			main="Dissimilarity Matrix")
		plotcolors(speo.color, rlabels=attributes(D)$Labels[spe.o], 
			main="Ordered Dissimilarity Matrix")
	}

	par(op)
}
```

```{r algae matrix}
##Cluster using nomclust

##Make a NULL dataset for the output from "nomclust"
#This makes a long dataset with all possible comparisons
algae_combdf <- combn(algae_imp2$species,2)
algae_comparison<-data.frame(algae_combdf[1,], algae_combdf[2,])
colnames(algae_comparison) <- c("c1", "c2")

#Select the variables to use from the imputed data
algae_dataSET <- algae_imp2[,c(1:11)]
algae_spnames <- algae_dataSET[,"species"]

#variables for the matrix
evaluation <- NULL
cmin = 2
cmax = 25


algae_dataSET2 <- data.frame(algae_dataSET[,-1], row.names = algae_dataSET[,1])

algae_nomclust_test <- nomclust(algae_dataSET2, measure = 'good2', method = 'average')

#extract groups and rename columns
algae_groups <- as.data.frame(algae_nomclust_test$mem)
algae_groups <- algae_groups %>% rename_with(~paste0("group_clu", sub("clu_*", "_", .)), 
                   starts_with('clu'))
#save evaluation metric
good2_eval <- melt(algae_nomclust_test$eval, id.vars = "cluster")
good2_eval$distance <- "Goodall2"
good2_eval$method <-  'average'
#append to dataset
algae_dataSET3 <- bind_cols(algae_dataSET, algae_groups)



#make distance matrix
algae_matrix <- good2(algae_dataSET2)


#legendre dissimilarity matrix
coldiss(algae_matrix) 

#mds
algaemds <- metaMDS(algae_matrix)

plot(algaemds)
coldiss(algae_matrix)
#save these as graphs for looking at later

#save matrix as R obejct and csv
algae_matrix2 <- fortify(algae_matrix)

save(algae_matrix, file = here('data','algae_matrix.RData'))
write.csv(algae_matrix2, file = here('data', 'clean', '20210606_algae_matrix.csv'))
```




```{r animal matrix}
##Cluster using nomclust

##Make a NULL dataset for the output from "nomclust"
#This makes a long dataset with all possible comparisons
animal_combdf <- combn(animal_imp2$species,2)
animal_comparison<-data.frame(animal_combdf[1,], animal_combdf[2,])
colnames(animal_comparison) <- c("c1", "c2")

#Select the variables to use from the imputed data
animal_dataSET <- animal_imp2[,c(1:14)]
animal_spnames <- animal_imp2[,"species"]

#other variables for matrix
evaluation <- NULL
cmin = 2
cmax = 25


animal_dataSET2 <- data.frame(animal_dataSET[,-1], row.names = animal_dataSET[,1])

animal_nomclust_test <- nomclust(animal_dataSET2, measure = 'good2', method = 'average')

#extract groups and rename columns
animal_groups <- as.data.frame(animal_nomclust_test$mem)
animal_groups <- animal_groups %>% rename_with(~paste0("group_clu", sub("clu_*", "_", .)), 
                   starts_with('clu'))
#save evaluation metric
animal_good2_eval <- melt(animal_nomclust_test$eval, id.vars = "cluster")
animal_good2_eval$distance <- "Goodall2"
animal_good2_eval$method <-  'average'
#append to dataset
animal_dataSET3 <- bind_cols(animal_dataSET, animal_groups)



#make distance matrix
animal_matrix <- good2(animal_dataSET2)


#legendre dissimilarity matrix
coldiss(animal_matrix) 

#mds
animalmds <- metaMDS(animal_matrix)

plot(animalmds)
coldiss(animal_matrix)
#save these as graphs for looking at later

animal_matrix2 <- fortify(animal_matrix)


save(animal_matrix, file = here('data','animal_matrix.RData'))
write.csv(animal_matrix2, file = here('data', 'clean', '20210606_animal_matrix.csv'))
```

```{r export graphs}
png(filename = here('output', '20210730_algae-dissimilarity.png'),
    width = 1000, height = 500,
    units = 'px')
coldiss(algae_matrix)
dev.off()


png(filename = here('output', '20210730_animal-dissimilarity.png'),
    width = 1000, height = 500,
    units = 'px')
coldiss(animal_matrix)
dev.off()
```


Data Evalutation
```{r}

```



```{r dendrograms}
#define options for heirarchcal clustering 
methodsClust <- c("single", "complete", "average")

######Algae  
#build the model and select the number of clusters
algae_fit <- hclust(algae_matrix, method = methodsClust[3])  #change cluster method
algae_clust <- cutree(algae_fit, 4)  # change number of clusters

#make into dendro data for plotting
algae_dendr <- dendro_data(algae_fit, type="rectangle") 
  
#add labels
algae_labs <- label(algae_dendr)
algae_labs$cluster <- as.factor(algae_clust)
  
algae_dendr_plot <- ggplot() +
  geom_segment(data=segment(algae_dendr), aes(x=x, y=y, xend=xend, yend=yend)) +
  geom_text(data=algae_labs, aes(x=x, y=y, label=label, hjust=0, color = cluster), size=2) +
  coord_flip() + scale_y_reverse(expand=c(0.1, 0), limits = c(.9,-0.1)) +
  theme_void()
  

algae_dendr_plot

ggsave(here('output', '20210730_algae-cluster-dendro.png'), plot = last_plot())

######Animals
animal_fit <- hclust(animal_matrix, method = methodsClust[3])  #change cluster method
animal_clust <- cutree(animal_fit, 8)  # change number of clusters

animal_dendr <- dendro_data(animal_fit, type="rectangle") 

animal_labs <- label(animal_dendr)
animal_labs$cluster <- as.factor(animal_clust)
  
animal_dendr_plot <- ggplot() +
  geom_segment(data=segment(animal_dendr), aes(x=x, y=y, xend=xend, yend=yend)) +
  geom_text(data=animal_labs, aes(x=x, y=y, label=label, hjust=0, color = cluster), size=2) +
  coord_flip() + scale_y_reverse(expand=c(0.1, 0), limits = c(.9,-0.1)) +
  theme_void()
  

animal_dendr_plot

ggsave(here('output', '20210730_animal-cluster-dendro.png'), plot = last_plot())
```

to do, probably figure out other coloring methods, if i can set k with rtsne, etc

```{r}
#algae_tsne <- tsne(algae_matrix, epoch = 100, perplexity = 3, k = 3)
#plot(algae_tsne)

tsne_obj_ag <- Rtsne(algae_matrix, is_distance = TRUE, perplexity = 5)
plot(tsne_obj_ag$Y)

tsne_plot_ag <- data.frame(x = tsne_obj_ag$Y[,1], y = tsne_obj_ag$Y[,2], 
                         algae_dataSET2)

tsne_algae <- ggplot(tsne_plot_ag, aes(x=x, y=y)) + 
  #geom_point(aes(color = common_name_division_bgr)) +
  geom_point(aes(color = morphology1)) +
  theme_classic()

tsne_algae

#ggsave(here('output', '20210730_algae-cluster-tsne2.png'), plot = last_plot())

## animals

animal_phyla <- trait_raw %>%
  subset(group %in% c('Invertebrate', 'Vertebrate')) %>%
  dplyr:::select(species, phylum)

tsne_obj_an <- Rtsne(animal_matrix, is_distance = TRUE, perplexity = 5)
plot(tsne_obj_an$Y)

tsne_plot_an <- data.frame(x = tsne_obj_an$Y[,1], y = tsne_obj_an$Y[,2], 
                         animal_dataSET2, animal_phyla)

tsne_animal <- ggplot(tsne_plot_an, aes(x=x, y=y)) + 
  #geom_point(aes(color = common_name_division_bgr)) +
  geom_point(aes(color = phylum)) +
  theme_classic()

tsne_animal

ggsave(here('output', '20210730_animal-cluster-tsne.png'), plot = last_plot())

```

